version: '3'
services:
  hajimi-app:
    build: .
    container_name: hajimi-app
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./hajimi:/hajimi
    restart: unless-stopped